# 🌐 General settings
title: "Alberto Cotumaccio's Website"
description: "Alberto Cotumaccio's website"
author: "Alberto Cotumaccio"
email: ""
language: en

# 📂 Base settings
baseurl: ""
url: "https://albertocotumaccio.github.io"

# 📄 File and directory settings
exclude:
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - ".jekyll-metadata"

# 🔗 Social media links
social:
  github: "https://github.com/albertoCotumaccio"
  linkedin: "https://www.linkedin.com/in/alberto-cotumaccio-8b8443229/"
  twitter: "https://twitter.com/Albecotu"


# 🎨 Theme e plugins
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# 🔄 Build settings
future: false


collections:  # non strettamente necessario se usi solo _posts/it e _posts/en
  posts_it:
    output: true
  posts_en:
    output: true


defaults:
  - scope:
      path: "" 
      type: "posts"
    values:
      layout: post

subtitle_blog:
  en: ""
  it: ""


# ignore warnings
sass:
  quiet_deps: true
  silence_deprecations:
    - import
    - global-builtin
    - color-functions
